name: AutoIssueSync Workflow

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore


    - name: Build and Run AutoIssueSync.Analyzer
      run: dotnet build AutoIssueSync.Analyzer/AutoIssueSync.Analyzer.csproj --configuration Release && dotnet AutoIssueSync.Analyzer/bin/Release/net6.0/AutoIssueSync.Analyzer.dll AutoIssueSync.Demo

    - name: List Directory Structure
      run: ls -R /home/runner/work/AutoIssueSync

    - name: Build AutoIssueSync.Sync
      run: dotnet build AutoIssueSync.Sync/AutoIssueSync.Sync.csproj --configuration Release

    - name: Run Issue Sync
      run: pwd &
           dotnet AutoIssueSync.Sync/bin/Release/net6.0/AutoIssueSync.Sync.dll issues.json
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

